spring:
  http:
    log-request-details: true
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.99.100/postgres
    username: postgres
    password: abc123
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework: debug

